[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "antidote-acta"
version = "0.2.2"
authors = [
    { name = "Cristian Cardellino", email = "cristian.a.cardellino@inria.fr" },
    { name = "Theo Alkibiades Collias", email = "theo-alkibiades.collias@inria.fr" }
]
description = "implementation of the 'Transformed-based Argument Mining' module"
readme = "README.md"
requires-python = ">=3.10.8"
dynamic = ["dependencies"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache v2.0 License"
]

[project.urls]
Homepage = "https://gitlab.com/wimmics-antidote/antidote-acta"
Issues = "https://gitlab.com/wimmics-antidote/antidote-acta/-/issues"

[tool.setuptools.packages.find]
include = ["acta*"]
exclude = ["*venv*", "*env*"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
